import type { AppState, CareerAssessment } from "./types";
import { uid } from "./id";

export function emptyCareerAssessment(): CareerAssessment {
  return {
    completed: false,
    skippedKnownCareer: false,
    interests: [],
    workEnvironments: [],
    workStyles: [],
    values: {},
    academicInterests: {},
    feedback: {},
    primaryCareerId: "",
  };
}

export function uid16() {
  return uid();
}

export function emptyState(): AppState {
  return {
    student: {
      id: uid(),
      firstName: "",
      lastName: "",
      email: "",
      age: "",
      highSchool: "",
      graduationYear: "2027",
      city: "",
      state: "",
      zip: "",
      country: "United States",
      latitude: null,
      longitude: null,
      locationPermission: false,
      firstGeneration: "",
      internationalStudent: "",
      citizenship: "",
      residencyStatus: "",
      backgroundSetting: "",
      militaryFamily: false,
      legacy: "",
      parentEducation: "",
      householdAidNotes: "",
      hispanicLatino: "",
      raceEthnicity: [],
    },
    academic: {
      weightedGpa: "",
      unweightedGpa: "",
      gpaScale: "4.0",
      classRank: "",
      classSize: "",
      percentile: "",
      gpaTrend: "",
      gpaTrendExplanation: "",
    },
    courses: [],
    testing: {
      sat: null,
      act: null,
      ap: [],
      ib: [],
      testOptional: false,
    },
    activities: [],
    work: [],
    awards: [],
    career: {
      intendedCareers: [],
      intendedMajors: [],
      industries: [],
      salaryRange: "",
      workEnvironment: [],
      geographicPreferences: [],
      workMode: [],
      companySize: [],
      graduateSchoolInterest: "Undecided",
      professionalSchoolInterest: "No",
    },
    careerAssessment: emptyCareerAssessment(),
    savedCareerIds: [],
    preferences: {
      academic: {
        majorStrength: "Neutral",
        classSize: "Neutral",
        research: "Neutral",
        professors: "Neutral",
        internships: "Neutral",
        careerPlacement: "Neutral",
        graduatePrep: "Neutral",
        honorsPrograms: "Neutral",
        studyAbroad: "Neutral",
        entrepreneurship: "Neutral",
        coop: "Neutral",
        doubleMajors: "Neutral",
        minors: "Neutral",
      },
      campusSliders: {
        schoolSize: 50,
        urbanRural: 50,
        traditionalModern: 50,
        classSize: 50,
      },
      campus: {
        greekLife: "Neutral",
        athletics: "Neutral",
        schoolSpirit: "Neutral",
        clubs: "Neutral",
        socialScene: "Neutral",
        diversityOfActivities: "Neutral",
        religiousEnvironment: "Neutral",
        politicalEnvironment: "Neutral",
        outdoorRecreation: "Neutral",
      },
      geographic: {
        preferredStates: [],
        considerStates: [],
        unwillingStates: [],
        maxDistanceMiles: "",
        climates: [],
        settings: [],
        airportAccess: "Neutral",
        publicTransit: "Neutral",
        distancePreset: "us",
        customMaxMiles: "",
        maxDriveTime: "none",
        travelMode: "Driving",
        attendanceScope: "us",
        inStateTuitionOnly: false,
      },
      lifestyle: { tags: [] },
      financial: {
        maxAnnualCost: "",
        financialAidImportance: "Neutral",
        needBasedAid: false,
        meritScholarships: false,
        willingOutOfState: true,
        maxStudentDebt: "",
      },
    },
    savedCollegeIds: [],
    banishedCollegeIds: [],
    compareIds: [],
    resumes: [],
    activeResumeId: null,
    onboardingComplete: false,
    accountEmail: null,
    profileRevisions: [],
  };
}

export function demoState(): AppState {
  const base = emptyState();
  return {
    ...base,
    onboardingComplete: true,
    student: {
      ...base.student,
      firstName: "Alex",
      lastName: "Rivera",
      email: "alex.rivera@email.com",
      age: "17",
      highSchool: "Westlake High School",
      graduationYear: "2027",
      city: "Austin",
      state: "TX",
      zip: "78746",
      country: "United States",
      latitude: 30.2672,
      longitude: -97.7431,
      locationPermission: false,
      firstGeneration: "Yes",
      internationalStudent: "No",
      citizenship: "U.S. citizen",
      residencyStatus: "In-state",
      backgroundSetting: "Suburban",
      militaryFamily: false,
      legacy: "",
      parentEducation: "Some college",
      householdAidNotes: "",
      hispanicLatino: "Yes",
      raceEthnicity: ["White"],
    },
    academic: {
      weightedGpa: "4.42",
      unweightedGpa: "3.91",
      gpaScale: "4.0",
      classRank: "24",
      classSize: "612",
      percentile: "4",
      gpaTrend: "increased",
      gpaTrendExplanation:
        "GPA rose from 3.7 as a freshman after I shifted into more advanced STEM coursework and better study systems.",
    },
    courses: [
      { id: uid(), name: "AP Calculus BC", subject: "Math", level: "AP", grade: "A", year: "11" },
      { id: uid(), name: "AP Computer Science A", subject: "Computer Science", level: "AP", grade: "A", year: "11" },
      { id: uid(), name: "AP Physics C: Mechanics", subject: "Science", level: "AP", grade: "A-", year: "11" },
      { id: uid(), name: "AP English Language", subject: "English", level: "AP", grade: "A-", year: "11" },
      { id: uid(), name: "AP US History", subject: "History", level: "AP", grade: "B+", year: "10" },
      { id: uid(), name: "Honors Chemistry", subject: "Science", level: "Honors", grade: "A", year: "10" },
      { id: uid(), name: "Dual Enrollment Macroeconomics", subject: "Social Science", level: "Dual Enrollment", grade: "A", year: "11" },
    ],
    testing: {
      sat: { total: "1440", readingWriting: "700", math: "740", date: "2025-10" },
      act: null,
      ap: [
        { id: uid(), subject: "Computer Science A", score: "5" },
        { id: uid(), subject: "Calculus BC", score: "4" },
        { id: uid(), subject: "English Language", score: "4" },
      ],
      ib: [],
      testOptional: false,
    },
    activities: [
      {
        id: uid(),
        name: "Computer Science Club",
        organization: "Westlake High School",
        category: "Technology",
        position: "President",
        yearsParticipated: "3",
        startDate: "2023-09",
        endDate: "Present",
        hoursPerWeek: "6",
        weeksPerYear: "36",
        hasLeadership: true,
        leadershipTitle: "President",
        peopleLed: "42",
        leadershipResponsibilities:
          "Run weekly meetings, mentor newer members, and coordinate competitions and guest speakers.",
        accomplishments:
          "Grew membership and launched a peer tutoring program for intro CS students.",
        createdSomething: true,
        grewMembership: true,
        raisedMoney: false,
        generatedRevenue: false,
        wonAward: true,
        organizedEvent: true,
        helpedPeople: true,
        peopleImpacted: "120",
        recognition: "Regional",
      },
      {
        id: uid(),
        name: "Nonprofit coding workshops",
        organization: "CodeNext Austin",
        category: "Community Service",
        position: "Lead Instructor",
        yearsParticipated: "2",
        startDate: "2024-06",
        endDate: "Present",
        hoursPerWeek: "4",
        weeksPerYear: "40",
        hasLeadership: true,
        leadershipTitle: "Lead Instructor",
        peopleLed: "6",
        leadershipResponsibilities: "Train volunteer instructors and design beginner Python workshops.",
        accomplishments: "Taught weekend workshops for middle school students from Title I schools.",
        createdSomething: true,
        grewMembership: false,
        raisedMoney: false,
        generatedRevenue: false,
        wonAward: false,
        organizedEvent: true,
        helpedPeople: true,
        peopleImpacted: "80",
        recognition: "None",
      },
      {
        id: uid(),
        name: "Varsity Cross Country",
        organization: "Westlake High School",
        category: "Athletics",
        position: "Varsity Runner",
        yearsParticipated: "4",
        startDate: "2023-08",
        endDate: "Present",
        hoursPerWeek: "12",
        weeksPerYear: "20",
        hasLeadership: false,
        leadershipTitle: "",
        peopleLed: "",
        leadershipResponsibilities: "",
        accomplishments: "Competed in district championships and helped host a community 5K fundraiser.",
        createdSomething: false,
        grewMembership: false,
        raisedMoney: true,
        generatedRevenue: false,
        wonAward: false,
        organizedEvent: true,
        helpedPeople: true,
        peopleImpacted: "200",
        recognition: "Regional",
      },
    ],
    work: [
      {
        id: uid(),
        employer: "Local software studio",
        position: "Summer intern",
        startDate: "2025-06",
        endDate: "2025-08",
        hoursPerWeek: "30",
        paid: "Paid",
        description: "Supported a small product team building internal tools for a logistics client.",
        accomplishments: "Shipped UI improvements and wrote test coverage for a customer dashboard.",
        leadershipResponsibilities: "",
        revenueGenerated: "",
        peopleManaged: "",
        quantifiableResults: "Reduced a recurring reporting task from 45 minutes to under 10 minutes.",
      },
    ],
    awards: [
      {
        id: uid(),
        name: "Regional Hackathon Finalist",
        organization: "Texas High School Hack",
        date: "2025-03",
        level: "Regional",
        description: "Built an accessibility tool that converts classroom PDFs into simpler reading formats.",
      },
      {
        id: uid(),
        name: "AP Scholar with Distinction",
        organization: "College Board",
        date: "2025-07",
        level: "National",
        description: "Earned qualifying scores on multiple AP exams.",
      },
    ],
    career: {
      intendedCareers: ["Software engineering", "Product management"],
      intendedMajors: ["Computer Science", "Business"],
      industries: ["Technology", "Finance", "Entrepreneurship"],
      salaryRange: "$80k–$120k starting",
      workEnvironment: ["Collaborative", "Fast-paced"],
      geographicPreferences: ["Texas", "West Coast", "Northeast"],
      workMode: ["Hybrid", "In-person"],
      companySize: ["Startup", "Mid-size", "Large"],
      graduateSchoolInterest: "Maybe later",
      professionalSchoolInterest: "No",
    },
    careerAssessment: {
      completed: true,
      skippedKnownCareer: false,
      interests: ["Working with technology", "Building something from scratch", "Solving a difficult problem", "Leading a team"],
      workEnvironments: ["Office", "Mostly remote", "A combination"],
      workStyles: ["figuringOut", "collaborating", "leading"],
      values: { highIncome: 4, intellectualChallenge: 5, creativity: 4, entrepreneurship: 4, workLifeBalance: 3 },
      academicInterests: { Technology: 5, Math: 4, Business: 4, Engineering: 4 },
      feedback: {},
      primaryCareerId: "software-engineer",
    },
    savedCareerIds: ["software-engineer", "product-manager", "financial-analyst"],
    preferences: {
      ...base.preferences,
      academic: {
        ...base.preferences.academic,
        majorStrength: "Very Important",
        internships: "Very Important",
        careerPlacement: "Very Important",
        entrepreneurship: "Important",
        research: "Important",
        classSize: "Important",
      },
      campusSliders: {
        schoolSize: 72,
        urbanRural: 35,
        traditionalModern: 50,
        classSize: 55,
      },
      geographic: {
        preferredStates: ["TX"],
        considerStates: ["OK", "LA", "AR", "NM"],
        unwillingStates: [],
        maxDistanceMiles: "250",
        climates: ["Warm", "Temperate"],
        settings: ["Urban", "Suburban"],
        airportAccess: "Important",
        publicTransit: "Neutral",
        distancePreset: "250",
        customMaxMiles: "",
        maxDriveTime: "180",
        travelMode: "Driving",
        attendanceScope: "state-neighbors",
        inStateTuitionOnly: false,
      },
      lifestyle: {
        tags: ["Major sports", "Concerts", "Restaurants", "Hiking", "Cultural activities"],
      },
      financial: {
        maxAnnualCost: "35000",
        financialAidImportance: "Important",
        needBasedAid: true,
        meritScholarships: true,
        willingOutOfState: true,
        maxStudentDebt: "25000",
      },
    },
    savedCollegeIds: ["ut-austin", "tamu", "rice", "umich", "acc"],
    banishedCollegeIds: [],
    compareIds: ["ut-austin", "georgia-tech", "rice"],
  };
}

export function studentName(state: AppState) {
  const n = `${state.student.firstName} ${state.student.lastName}`.trim();
  return n || "Student";
}

export function parseNum(value: string | number | undefined | null): number | null {
  if (value === undefined || value === null || value === "") return null;
  const n = typeof value === "number" ? value : Number(String(value).replace(/[,$]/g, ""));
  return Number.isFinite(n) ? n : null;
}

/** Normalize student GPA to a ~4.0 scale for comparisons with published averages. */
export function gpaOnFour(state: AppState): number | null {
  const raw = parseNum(state.academic.unweightedGpa) ?? parseNum(state.academic.weightedGpa);
  if (raw === null) return null;
  if (state.academic.gpaScale === "100") return Math.min(4.3, (raw / 100) * 4);
  if (state.academic.gpaScale === "5.0") return Math.min(4.3, (raw / 5) * 4);
  return raw;
}
